# Generated by Django 5.2.3 on 2025-06-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='chemin_pdf',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
